openapi: 3.0.1
info:
  title: Identity.TermsOfUse
  version: v1.0-beta
servers:
  - url: https://graph.microsoft.com/beta/
    description: Core
paths:
  /agreementAcceptances:
    get:
      tags:
        - agreementAcceptances.agreementAcceptance
      summary: Get entities from agreementAcceptances
      operationId: agreementAcceptances.agreementAcceptance_ListAgreementAcceptance
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - agreementId
                - agreementId desc
                - userId
                - userId desc
                - agreementFileId
                - agreementFileId desc
                - recordedDateTime
                - recordedDateTime desc
                - userDisplayName
                - userDisplayName desc
                - userPrincipalName
                - userPrincipalName desc
                - userEmail
                - userEmail desc
                - state
                - state desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - agreementId
                - userId
                - agreementFileId
                - recordedDateTime
                - userDisplayName
                - userPrincipalName
                - userEmail
                - state
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of agreementAcceptance
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.agreementAcceptance'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - agreementAcceptances.agreementAcceptance
      summary: Add new entity to agreementAcceptances
      operationId: agreementAcceptances.agreementAcceptance_CreateAgreementAcceptance
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.agreementAcceptance'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.agreementAcceptance'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/agreementAcceptances/{agreementAcceptance-id}':
    get:
      tags:
        - agreementAcceptances.agreementAcceptance
      summary: Get entity from agreementAcceptances by key
      operationId: agreementAcceptances.agreementAcceptance_GetAgreementAcceptance
      parameters:
        - name: agreementAcceptance-id
          in: path
          description: 'key: agreementAcceptance-id of agreementAcceptance'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreementAcceptance
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - agreementId
                - userId
                - agreementFileId
                - recordedDateTime
                - userDisplayName
                - userPrincipalName
                - userEmail
                - state
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.agreementAcceptance'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - agreementAcceptances.agreementAcceptance
      summary: Update entity in agreementAcceptances
      operationId: agreementAcceptances.agreementAcceptance_UpdateAgreementAcceptance
      parameters:
        - name: agreementAcceptance-id
          in: path
          description: 'key: agreementAcceptance-id of agreementAcceptance'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreementAcceptance
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.agreementAcceptance'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - agreementAcceptances.agreementAcceptance
      summary: Delete entity from agreementAcceptances
      operationId: agreementAcceptances.agreementAcceptance_DeleteAgreementAcceptance
      parameters:
        - name: agreementAcceptance-id
          in: path
          description: 'key: agreementAcceptance-id of agreementAcceptance'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreementAcceptance
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  /agreements:
    get:
      tags:
        - agreements.agreement
      summary: Get entities from agreements
      operationId: agreements.agreement_ListAgreement
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - displayName
                - displayName desc
                - isViewingBeforeAcceptanceRequired
                - isViewingBeforeAcceptanceRequired desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - isViewingBeforeAcceptanceRequired
                - files
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - files
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of agreement
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.agreement'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - agreements.agreement
      summary: Add new entity to agreements
      operationId: agreements.agreement_CreateAgreement
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.agreement'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.agreement'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/agreements/{agreement-id}':
    get:
      tags:
        - agreements.agreement
      summary: Get entity from agreements by key
      operationId: agreements.agreement_GetAgreement
      parameters:
        - name: agreement-id
          in: path
          description: 'key: agreement-id of agreement'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreement
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - isViewingBeforeAcceptanceRequired
                - files
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - files
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.agreement'
          links:
            files:
              operationId: agreements.agreement.GetAgreement
              parameters:
                id: $request.path.id
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - agreements.agreement
      summary: Update entity in agreements
      operationId: agreements.agreement_UpdateAgreement
      parameters:
        - name: agreement-id
          in: path
          description: 'key: agreement-id of agreement'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreement
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.agreement'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - agreements.agreement
      summary: Delete entity from agreements
      operationId: agreements.agreement_DeleteAgreement
      parameters:
        - name: agreement-id
          in: path
          description: 'key: agreement-id of agreement'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreement
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/agreements/{agreement-id}/files':
    get:
      tags:
        - agreements.agreementFile
      summary: Get files from agreements
      operationId: agreements_ListFiles
      parameters:
        - name: agreement-id
          in: path
          description: 'key: agreement-id of agreement'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreement
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - language
                - language desc
                - fileName
                - fileName desc
                - fileData
                - fileData desc
                - isDefault
                - isDefault desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - language
                - fileName
                - fileData
                - isDefault
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of agreementFile
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.agreementFile'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - agreements.agreementFile
      summary: Create new navigation property to files for agreements
      operationId: agreements_CreateFiles
      parameters:
        - name: agreement-id
          in: path
          description: 'key: agreement-id of agreement'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreement
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.agreementFile'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.agreementFile'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/agreements/{agreement-id}/files/{agreementFile-id}':
    get:
      tags:
        - agreements.agreementFile
      summary: Get files from agreements
      operationId: agreements_GetFiles
      parameters:
        - name: agreement-id
          in: path
          description: 'key: agreement-id of agreement'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreement
        - name: agreementFile-id
          in: path
          description: 'key: agreementFile-id of agreementFile'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreementFile
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - language
                - fileName
                - fileData
                - isDefault
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.agreementFile'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - agreements.agreementFile
      summary: Update the navigation property files in agreements
      operationId: agreements_UpdateFiles
      parameters:
        - name: agreement-id
          in: path
          description: 'key: agreement-id of agreement'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreement
        - name: agreementFile-id
          in: path
          description: 'key: agreementFile-id of agreementFile'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreementFile
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.agreementFile'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/users/{user-id}/agreementAcceptances':
    get:
      tags:
        - users.agreementAcceptance
      summary: Get agreementAcceptances from users
      operationId: users_ListAgreementAcceptances
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - agreementId
                - agreementId desc
                - userId
                - userId desc
                - agreementFileId
                - agreementFileId desc
                - recordedDateTime
                - recordedDateTime desc
                - userDisplayName
                - userDisplayName desc
                - userPrincipalName
                - userPrincipalName desc
                - userEmail
                - userEmail desc
                - state
                - state desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - agreementId
                - userId
                - agreementFileId
                - recordedDateTime
                - userDisplayName
                - userPrincipalName
                - userEmail
                - state
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of agreementAcceptance
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.agreementAcceptance'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/users/{user-id}/agreementAcceptances/{agreementAcceptance-id}':
    get:
      tags:
        - users.agreementAcceptance
      summary: Get agreementAcceptances from users
      operationId: users_GetAgreementAcceptances
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: agreementAcceptance-id
          in: path
          description: 'key: agreementAcceptance-id of agreementAcceptance'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: agreementAcceptance
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - agreementId
                - userId
                - agreementFileId
                - recordedDateTime
                - userDisplayName
                - userPrincipalName
                - userEmail
                - state
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.agreementAcceptance'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.agreementAcceptance:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: agreementAcceptance
          type: object
          properties:
            agreementId:
              type: string
              nullable: true
            userId:
              type: string
              nullable: true
            agreementFileId:
              type: string
              nullable: true
            recordedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            userDisplayName:
              type: string
              nullable: true
            userPrincipalName:
              type: string
              nullable: true
            userEmail:
              type: string
              nullable: true
            state:
              $ref: '#/components/schemas/microsoft.graph.agreementAcceptanceState'
      example:
        id: string (identifier)
        agreementId: string
        userId: string
        agreementFileId: string
        recordedDateTime: string (timestamp)
        userDisplayName: string
        userPrincipalName: string
        userEmail: string
        state:
          '@odata.type': microsoft.graph.agreementAcceptanceState
    microsoft.graph.agreement:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: agreement
          type: object
          properties:
            displayName:
              type: string
              nullable: true
            isViewingBeforeAcceptanceRequired:
              type: boolean
              nullable: true
            files:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.agreementFile'
      example:
        id: string (identifier)
        displayName: string
        isViewingBeforeAcceptanceRequired: true
        files:
          - '@odata.type': microsoft.graph.agreementFile
    microsoft.graph.agreementFile:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: agreementFile
          type: object
          properties:
            language:
              type: string
              nullable: true
            fileName:
              type: string
              nullable: true
            fileData:
              $ref: '#/components/schemas/microsoft.graph.agreementFileData'
            isDefault:
              type: boolean
              nullable: true
      example:
        id: string (identifier)
        language: string
        fileName: string
        fileData:
          '@odata.type': microsoft.graph.agreementFileData
        isDefault: true
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
          description: Read-only.
      example:
        id: string (identifier)
    microsoft.graph.agreementAcceptanceState:
      title: agreementAcceptanceState
      enum:
        - accepted
        - declined
      type: string
    microsoft.graph.agreementFileData:
      title: agreementFileData
      type: object
      properties:
        data:
          type: string
          format: base64url
          nullable: true
      example:
        data: string
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]