openapi: 3.0.1
info:
  title: Identity.Protection
  version: v1.0-beta
servers:
  - url: https://graph.microsoft.com/beta/
    description: Core
paths:
  /riskDetections:
    get:
      tags:
        - riskDetections.riskDetection
      summary: Get entities from riskDetections
      operationId: riskDetections.riskDetection_ListRiskDetection
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - requestId
                - requestId desc
                - correlationId
                - correlationId desc
                - riskEventType
                - riskEventType desc
                - riskType
                - riskType desc
                - riskState
                - riskState desc
                - riskLevel
                - riskLevel desc
                - riskDetail
                - riskDetail desc
                - source
                - source desc
                - detectionTimingType
                - detectionTimingType desc
                - activity
                - activity desc
                - tokenIssuerType
                - tokenIssuerType desc
                - ipAddress
                - ipAddress desc
                - location
                - location desc
                - activityDateTime
                - activityDateTime desc
                - detectedDateTime
                - detectedDateTime desc
                - lastUpdatedDateTime
                - lastUpdatedDateTime desc
                - userId
                - userId desc
                - userDisplayName
                - userDisplayName desc
                - userPrincipalName
                - userPrincipalName desc
                - additionalInfo
                - additionalInfo desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - requestId
                - correlationId
                - riskEventType
                - riskType
                - riskState
                - riskLevel
                - riskDetail
                - source
                - detectionTimingType
                - activity
                - tokenIssuerType
                - ipAddress
                - location
                - activityDateTime
                - detectedDateTime
                - lastUpdatedDateTime
                - userId
                - userDisplayName
                - userPrincipalName
                - additionalInfo
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of riskDetection
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.riskDetection'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - riskDetections.riskDetection
      summary: Add new entity to riskDetections
      operationId: riskDetections.riskDetection_CreateRiskDetection
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.riskDetection'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.riskDetection'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/riskDetections/{riskDetection-id}':
    get:
      tags:
        - riskDetections.riskDetection
      summary: Get entity from riskDetections by key
      operationId: riskDetections.riskDetection_GetRiskDetection
      parameters:
        - name: riskDetection-id
          in: path
          description: 'key: riskDetection-id of riskDetection'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskDetection
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - requestId
                - correlationId
                - riskEventType
                - riskType
                - riskState
                - riskLevel
                - riskDetail
                - source
                - detectionTimingType
                - activity
                - tokenIssuerType
                - ipAddress
                - location
                - activityDateTime
                - detectedDateTime
                - lastUpdatedDateTime
                - userId
                - userDisplayName
                - userPrincipalName
                - additionalInfo
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.riskDetection'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - riskDetections.riskDetection
      summary: Update entity in riskDetections
      operationId: riskDetections.riskDetection_UpdateRiskDetection
      parameters:
        - name: riskDetection-id
          in: path
          description: 'key: riskDetection-id of riskDetection'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskDetection
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.riskDetection'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - riskDetections.riskDetection
      summary: Delete entity from riskDetections
      operationId: riskDetections.riskDetection_DeleteRiskDetection
      parameters:
        - name: riskDetection-id
          in: path
          description: 'key: riskDetection-id of riskDetection'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskDetection
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  /riskyUsers:
    get:
      tags:
        - riskyUsers.riskyUser
      summary: Get entities from riskyUsers
      operationId: riskyUsers.riskyUser_ListRiskyUser
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - isDeleted
                - isDeleted desc
                - isProcessing
                - isProcessing desc
                - riskLastUpdatedDateTime
                - riskLastUpdatedDateTime desc
                - riskLevel
                - riskLevel desc
                - riskState
                - riskState desc
                - riskDetail
                - riskDetail desc
                - userDisplayName
                - userDisplayName desc
                - userPrincipalName
                - userPrincipalName desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isDeleted
                - isProcessing
                - riskLastUpdatedDateTime
                - riskLevel
                - riskState
                - riskDetail
                - userDisplayName
                - userPrincipalName
                - history
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - history
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of riskyUser
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.riskyUser'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - riskyUsers.riskyUser
      summary: Add new entity to riskyUsers
      operationId: riskyUsers.riskyUser_CreateRiskyUser
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.riskyUser'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.riskyUser'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/riskyUsers/{riskyUser-id}':
    get:
      tags:
        - riskyUsers.riskyUser
      summary: Get entity from riskyUsers by key
      operationId: riskyUsers.riskyUser_GetRiskyUser
      parameters:
        - name: riskyUser-id
          in: path
          description: 'key: riskyUser-id of riskyUser'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUser
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isDeleted
                - isProcessing
                - riskLastUpdatedDateTime
                - riskLevel
                - riskState
                - riskDetail
                - userDisplayName
                - userPrincipalName
                - history
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - history
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.riskyUser'
          links:
            history:
              operationId: riskyUsers.GetHistory
              parameters:
                riskyUser-id: $request.path.riskyUser-id
                riskyUserHistoryItem-id: $response.body#/id
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - riskyUsers.riskyUser
      summary: Update entity in riskyUsers
      operationId: riskyUsers.riskyUser_UpdateRiskyUser
      parameters:
        - name: riskyUser-id
          in: path
          description: 'key: riskyUser-id of riskyUser'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUser
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.riskyUser'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - riskyUsers.riskyUser
      summary: Delete entity from riskyUsers
      operationId: riskyUsers.riskyUser_DeleteRiskyUser
      parameters:
        - name: riskyUser-id
          in: path
          description: 'key: riskyUser-id of riskyUser'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUser
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/riskyUsers/{riskyUser-id}/history':
    get:
      tags:
        - riskyUsers.riskyUserHistoryItem
      summary: Get history from riskyUsers
      operationId: riskyUsers_ListHistory
      parameters:
        - name: riskyUser-id
          in: path
          description: 'key: riskyUser-id of riskyUser'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUser
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - isDeleted
                - isDeleted desc
                - isProcessing
                - isProcessing desc
                - riskLastUpdatedDateTime
                - riskLastUpdatedDateTime desc
                - riskLevel
                - riskLevel desc
                - riskState
                - riskState desc
                - riskDetail
                - riskDetail desc
                - userDisplayName
                - userDisplayName desc
                - userPrincipalName
                - userPrincipalName desc
                - userId
                - userId desc
                - initiatedBy
                - initiatedBy desc
                - activity
                - activity desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isDeleted
                - isProcessing
                - riskLastUpdatedDateTime
                - riskLevel
                - riskState
                - riskDetail
                - userDisplayName
                - userPrincipalName
                - userId
                - initiatedBy
                - activity
                - history
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - history
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of riskyUserHistoryItem
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.riskyUserHistoryItem'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - riskyUsers.riskyUserHistoryItem
      summary: Create new navigation property to history for riskyUsers
      operationId: riskyUsers_CreateHistory
      parameters:
        - name: riskyUser-id
          in: path
          description: 'key: riskyUser-id of riskyUser'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUser
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.riskyUserHistoryItem'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.riskyUserHistoryItem'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/riskyUsers/{riskyUser-id}/history/{riskyUserHistoryItem-id}':
    get:
      tags:
        - riskyUsers.riskyUserHistoryItem
      summary: Get history from riskyUsers
      operationId: riskyUsers_GetHistory
      parameters:
        - name: riskyUser-id
          in: path
          description: 'key: riskyUser-id of riskyUser'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUser
        - name: riskyUserHistoryItem-id
          in: path
          description: 'key: riskyUserHistoryItem-id of riskyUserHistoryItem'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUserHistoryItem
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isDeleted
                - isProcessing
                - riskLastUpdatedDateTime
                - riskLevel
                - riskState
                - riskDetail
                - userDisplayName
                - userPrincipalName
                - userId
                - initiatedBy
                - activity
                - history
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - history
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.riskyUserHistoryItem'
        default:
          $ref: '#/components/responses/error'
    patch:
      tags:
        - riskyUsers.riskyUserHistoryItem
      summary: Update the navigation property history in riskyUsers
      operationId: riskyUsers_UpdateHistory
      parameters:
        - name: riskyUser-id
          in: path
          description: 'key: riskyUser-id of riskyUser'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUser
        - name: riskyUserHistoryItem-id
          in: path
          description: 'key: riskyUserHistoryItem-id of riskyUserHistoryItem'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: riskyUserHistoryItem
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.riskyUserHistoryItem'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  /riskyUsers/microsoft.graph.confirmCompromised:
    post:
      tags:
        - riskyUsers.Actions
      summary: Invoke action confirmCompromised
      operationId: riskyUsers_confirmCompromised
      requestBody:
        description: Action parameters
        content:
          application/json:
            schema:
              type: object
              properties:
                userIds:
                  type: array
                  items:
                    type: string
                    nullable: true
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: action
  /riskyUsers/microsoft.graph.dismiss:
    post:
      tags:
        - riskyUsers.Actions
      summary: Invoke action dismiss
      operationId: riskyUsers_dismiss
      requestBody:
        description: Action parameters
        content:
          application/json:
            schema:
              type: object
              properties:
                userIds:
                  type: array
                  items:
                    type: string
                    nullable: true
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: action
components:
  schemas:
    microsoft.graph.riskDetection:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: riskDetection
          type: object
          properties:
            requestId:
              type: string
              nullable: true
            correlationId:
              type: string
              nullable: true
            riskEventType:
              type: string
              nullable: true
            riskType:
              $ref: '#/components/schemas/microsoft.graph.riskEventType'
            riskState:
              $ref: '#/components/schemas/microsoft.graph.riskState'
            riskLevel:
              $ref: '#/components/schemas/microsoft.graph.riskLevel'
            riskDetail:
              $ref: '#/components/schemas/microsoft.graph.riskDetail'
            source:
              type: string
              nullable: true
            detectionTimingType:
              $ref: '#/components/schemas/microsoft.graph.riskDetectionTimingType'
            activity:
              $ref: '#/components/schemas/microsoft.graph.activityType'
            tokenIssuerType:
              $ref: '#/components/schemas/microsoft.graph.tokenIssuerType'
            ipAddress:
              type: string
              nullable: true
            location:
              $ref: '#/components/schemas/microsoft.graph.signInLocation'
            activityDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            detectedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            lastUpdatedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            userId:
              type: string
              nullable: true
            userDisplayName:
              type: string
              nullable: true
            userPrincipalName:
              type: string
              nullable: true
            additionalInfo:
              type: string
              nullable: true
      example:
        id: string (identifier)
        requestId: string
        correlationId: string
        riskEventType: string
        riskType:
          '@odata.type': microsoft.graph.riskEventType
        riskState:
          '@odata.type': microsoft.graph.riskState
        riskLevel:
          '@odata.type': microsoft.graph.riskLevel
        riskDetail:
          '@odata.type': microsoft.graph.riskDetail
        source: string
        detectionTimingType:
          '@odata.type': microsoft.graph.riskDetectionTimingType
        activity:
          '@odata.type': microsoft.graph.activityType
        tokenIssuerType:
          '@odata.type': microsoft.graph.tokenIssuerType
        ipAddress: string
        location:
          '@odata.type': microsoft.graph.signInLocation
        activityDateTime: string (timestamp)
        detectedDateTime: string (timestamp)
        lastUpdatedDateTime: string (timestamp)
        userId: string
        userDisplayName: string
        userPrincipalName: string
        additionalInfo: string
    microsoft.graph.riskyUser:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: riskyUser
          type: object
          properties:
            isDeleted:
              type: boolean
              nullable: true
            isProcessing:
              type: boolean
              nullable: true
            riskLastUpdatedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            riskLevel:
              $ref: '#/components/schemas/microsoft.graph.riskLevel'
            riskState:
              $ref: '#/components/schemas/microsoft.graph.riskState'
            riskDetail:
              $ref: '#/components/schemas/microsoft.graph.riskDetail'
            userDisplayName:
              type: string
              nullable: true
            userPrincipalName:
              type: string
              nullable: true
            history:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.riskyUserHistoryItem'
      example:
        id: string (identifier)
        isDeleted: true
        isProcessing: true
        riskLastUpdatedDateTime: string (timestamp)
        riskLevel:
          '@odata.type': microsoft.graph.riskLevel
        riskState:
          '@odata.type': microsoft.graph.riskState
        riskDetail:
          '@odata.type': microsoft.graph.riskDetail
        userDisplayName: string
        userPrincipalName: string
        history:
          - '@odata.type': microsoft.graph.riskyUserHistoryItem
    microsoft.graph.riskyUserHistoryItem:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.riskyUser'
        - title: riskyUserHistoryItem
          type: object
          properties:
            userId:
              type: string
              nullable: true
            initiatedBy:
              type: string
              nullable: true
            activity:
              $ref: '#/components/schemas/microsoft.graph.riskUserActivity'
      example:
        id: string (identifier)
        isDeleted: true
        isProcessing: true
        riskLastUpdatedDateTime: string (timestamp)
        riskLevel:
          '@odata.type': microsoft.graph.riskLevel
        riskState:
          '@odata.type': microsoft.graph.riskState
        riskDetail:
          '@odata.type': microsoft.graph.riskDetail
        userDisplayName: string
        userPrincipalName: string
        history:
          - '@odata.type': microsoft.graph.riskyUserHistoryItem
        userId: string
        initiatedBy: string
        activity:
          '@odata.type': microsoft.graph.riskUserActivity
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
          description: Read-only.
      example:
        id: string (identifier)
    microsoft.graph.riskEventType:
      title: riskEventType
      enum:
        - unlikelyTravel
        - anonymizedIPAddress
        - maliciousIPAddress
        - unfamiliarFeatures
        - malwareInfectedIPAddress
        - suspiciousIPAddress
        - leakedCredentials
        - investigationsThreatIntelligence
        - generic
        - adminConfirmedUserCompromised
        - mcasImpossibleTravel
        - mcasSuspiciousInboxManipulationRules
        - investigationsThreatIntelligenceSigninLinked
        - maliciousIPAddressValidCredentialsBlockedIP
        - unknownFutureValue
      type: string
    microsoft.graph.riskState:
      title: riskState
      enum:
        - none
        - confirmedSafe
        - remediated
        - dismissed
        - atRisk
        - confirmedCompromised
        - unknownFutureValue
      type: string
    microsoft.graph.riskLevel:
      title: riskLevel
      enum:
        - low
        - medium
        - high
        - hidden
        - none
        - unknownFutureValue
      type: string
    microsoft.graph.riskDetail:
      title: riskDetail
      enum:
        - none
        - adminGeneratedTemporaryPassword
        - userPerformedSecuredPasswordChange
        - userPerformedSecuredPasswordReset
        - adminConfirmedSigninSafe
        - aiConfirmedSigninSafe
        - userPassedMFADrivenByRiskBasedPolicy
        - adminDismissedAllRiskForUser
        - adminConfirmedSigninCompromised
        - hidden
        - adminConfirmedUserCompromised
        - unknownFutureValue
      type: string
    microsoft.graph.riskDetectionTimingType:
      title: riskDetectionTimingType
      enum:
        - notDefined
        - realtime
        - nearRealtime
        - offline
        - unknownFutureValue
      type: string
    microsoft.graph.activityType:
      title: activityType
      enum:
        - signin
        - user
        - unknownFutureValue
      type: string
    microsoft.graph.tokenIssuerType:
      title: tokenIssuerType
      enum:
        - AzureAD
        - ADFederationServices
        - UnknownFutureValue
      type: string
    microsoft.graph.signInLocation:
      title: signInLocation
      type: object
      properties:
        city:
          type: string
          description: Provides the city where the sign-in originated. This is calculated using latitude/longitude information from the sign-in activity.
          nullable: true
        state:
          type: string
          description: Provides the State where the sign-in originated. This is calculated using latitude/longitude information from the sign-in activity.
          nullable: true
        countryOrRegion:
          type: string
          description: Provides the country code info (2 letter code) where the sign-in originated.  This is calculated using latitude/longitude information from the sign-in activity.
          nullable: true
        geoCoordinates:
          $ref: '#/components/schemas/microsoft.graph.geoCoordinates'
      example:
        city: string
        state: string
        countryOrRegion: string
        geoCoordinates:
          '@odata.type': microsoft.graph.geoCoordinates
    microsoft.graph.riskUserActivity:
      title: riskUserActivity
      type: object
      properties:
        eventTypes:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.riskEventType'
        riskEventTypes:
          type: array
          items:
            type: string
            nullable: true
        detail:
          $ref: '#/components/schemas/microsoft.graph.riskDetail'
      example:
        eventTypes:
          - '@odata.type': microsoft.graph.riskEventType
        riskEventTypes:
          - string
        detail:
          '@odata.type': microsoft.graph.riskDetail
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    microsoft.graph.geoCoordinates:
      title: geoCoordinates
      type: object
      properties:
        altitude:
          type: number
          description: 'Optional. The altitude (height), in feet,  above sea level for the item. Read-only.'
          format: double
          nullable: true
        latitude:
          type: number
          description: 'Optional. The latitude, in decimal, for the item. Read-only.'
          format: double
          nullable: true
        longitude:
          type: number
          description: 'Optional. The longitude, in decimal, for the item. Read-only.'
          format: double
          nullable: true
      example:
        altitude: double
        latitude: double
        longitude: double
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]