openapi: 3.0.1
info:
  title: OnlineMeetings
  version: v1.0-Beta
servers:
  - url: https://graph.microsoft.com/Beta/
    description: Core
paths:
  '/users/{user-id}/onlineMeetings':
    get:
      tags:
        - users.onlineMeeting
      summary: Get onlineMeetings from users
      operationId: users_ListOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - creationDateTime
                - creationDateTime desc
                - startDateTime
                - startDateTime desc
                - endDateTime
                - endDateTime desc
                - canceledDateTime
                - canceledDateTime desc
                - expirationDateTime
                - expirationDateTime desc
                - entryExitAnnouncement
                - entryExitAnnouncement desc
                - joinUrl
                - joinUrl desc
                - subject
                - subject desc
                - isCancelled
                - isCancelled desc
                - participants
                - participants desc
                - isBroadcast
                - isBroadcast desc
                - accessLevel
                - accessLevel desc
                - capabilities
                - capabilities desc
                - audioConferencing
                - audioConferencing desc
                - chatInfo
                - chatInfo desc
                - videoTeleconferenceId
                - videoTeleconferenceId desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - creationDateTime
                - startDateTime
                - endDateTime
                - canceledDateTime
                - expirationDateTime
                - entryExitAnnouncement
                - joinUrl
                - subject
                - isCancelled
                - participants
                - isBroadcast
                - accessLevel
                - capabilities
                - audioConferencing
                - chatInfo
                - videoTeleconferenceId
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of onlineMeeting
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - users.onlineMeeting
      summary: Create new navigation property to onlineMeetings for users
      operationId: users_CreateOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/users/{user-id}/onlineMeetings/{onlineMeeting-id}':
    get:
      tags:
        - users.onlineMeeting
      summary: Get onlineMeetings from users
      operationId: users_GetOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: onlineMeeting-id
          in: path
          description: 'key: onlineMeeting-id of onlineMeeting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: onlineMeeting
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - creationDateTime
                - startDateTime
                - endDateTime
                - canceledDateTime
                - expirationDateTime
                - entryExitAnnouncement
                - joinUrl
                - subject
                - isCancelled
                - participants
                - isBroadcast
                - accessLevel
                - capabilities
                - audioConferencing
                - chatInfo
                - videoTeleconferenceId
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - users.onlineMeeting
      summary: Update the navigation property onlineMeetings in users
      operationId: users_UpdateOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: onlineMeeting-id
          in: path
          description: 'key: onlineMeeting-id of onlineMeeting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: onlineMeeting
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.onlineMeeting:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: onlineMeeting
          type: object
          properties:
            creationDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            startDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            endDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            canceledDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            expirationDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            entryExitAnnouncement:
              type: boolean
              nullable: true
            joinUrl:
              type: string
              nullable: true
            subject:
              type: string
              nullable: true
            isCancelled:
              type: boolean
              nullable: true
            participants:
              $ref: '#/components/schemas/microsoft.graph.meetingParticipants'
            isBroadcast:
              type: boolean
              nullable: true
            accessLevel:
              $ref: '#/components/schemas/microsoft.graph.accessLevel'
            capabilities:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.meetingCapabilities'
            audioConferencing:
              $ref: '#/components/schemas/microsoft.graph.audioConferencing'
            chatInfo:
              $ref: '#/components/schemas/microsoft.graph.chatInfo'
            videoTeleconferenceId:
              type: string
              nullable: true
      example:
        id: string (identifier)
        creationDateTime: string (timestamp)
        startDateTime: string (timestamp)
        endDateTime: string (timestamp)
        canceledDateTime: string (timestamp)
        expirationDateTime: string (timestamp)
        entryExitAnnouncement: true
        joinUrl: string
        subject: string
        isCancelled: true
        participants:
          '@odata.type': microsoft.graph.meetingParticipants
        isBroadcast: true
        accessLevel:
          '@odata.type': microsoft.graph.accessLevel
        capabilities:
          - '@odata.type': microsoft.graph.meetingCapabilities
        audioConferencing:
          '@odata.type': microsoft.graph.audioConferencing
        chatInfo:
          '@odata.type': microsoft.graph.chatInfo
        videoTeleconferenceId: string
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
      example:
        id: string (identifier)
    microsoft.graph.meetingParticipants:
      title: meetingParticipants
      type: object
      properties:
        organizer:
          $ref: '#/components/schemas/microsoft.graph.meetingParticipantInfo'
        attendees:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.meetingParticipantInfo'
        producers:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.meetingParticipantInfo'
        contributors:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.meetingParticipantInfo'
      example:
        organizer:
          '@odata.type': microsoft.graph.meetingParticipantInfo
        attendees:
          - '@odata.type': microsoft.graph.meetingParticipantInfo
        producers:
          - '@odata.type': microsoft.graph.meetingParticipantInfo
        contributors:
          - '@odata.type': microsoft.graph.meetingParticipantInfo
    microsoft.graph.accessLevel:
      title: accessLevel
      enum:
        - everyone
        - invited
        - locked
        - sameEnterprise
        - sameEnterpriseAndFederated
      type: string
    microsoft.graph.meetingCapabilities:
      title: meetingCapabilities
      enum:
        - questionAndAnswer
        - unknownFutureValue
      type: string
    microsoft.graph.audioConferencing:
      title: audioConferencing
      type: object
      properties:
        conferenceId:
          type: string
          nullable: true
        tollNumber:
          type: string
          nullable: true
        tollFreeNumber:
          type: string
          nullable: true
        dialinUrl:
          type: string
          nullable: true
      example:
        conferenceId: string
        tollNumber: string
        tollFreeNumber: string
        dialinUrl: string
    microsoft.graph.chatInfo:
      title: chatInfo
      type: object
      properties:
        threadId:
          type: string
          nullable: true
        messageId:
          type: string
          nullable: true
        replyChainMessageId:
          type: string
          nullable: true
      example:
        threadId: string
        messageId: string
        replyChainMessageId: string
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    microsoft.graph.meetingParticipantInfo:
      title: meetingParticipantInfo
      type: object
      properties:
        identity:
          $ref: '#/components/schemas/microsoft.graph.identitySet'
        upn:
          type: string
          nullable: true
      example:
        identity:
          '@odata.type': microsoft.graph.identitySet
        upn: string
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    microsoft.graph.identitySet:
      title: identitySet
      type: object
      properties:
        application:
          $ref: '#/components/schemas/microsoft.graph.identity'
        device:
          $ref: '#/components/schemas/microsoft.graph.identity'
        user:
          $ref: '#/components/schemas/microsoft.graph.identity'
      example:
        application:
          '@odata.type': microsoft.graph.identity
        device:
          '@odata.type': microsoft.graph.identity
        user:
          '@odata.type': microsoft.graph.identity
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
    microsoft.graph.identity:
      title: identity
      type: object
      properties:
        id:
          type: string
          nullable: true
        displayName:
          type: string
          nullable: true
      example:
        id: string
        displayName: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]