openapi: 3.0.1
info:
  title: Users.Devices
  version: v1.0-beta
servers:
  - url: https://graph.microsoft.com/beta/
    description: Core
paths:
  '/users/{user-id}/devices':
    get:
      tags:
        - users.device
      summary: Get devices from users
      operationId: users_ListDevices
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - deletedDateTime
                - deletedDateTime desc
                - accountEnabled
                - accountEnabled desc
                - alternativeSecurityIds
                - alternativeSecurityIds desc
                - approximateLastSignInDateTime
                - approximateLastSignInDateTime desc
                - complianceExpirationDateTime
                - complianceExpirationDateTime desc
                - deviceId
                - deviceId desc
                - deviceMetadata
                - deviceMetadata desc
                - deviceVersion
                - deviceVersion desc
                - displayName
                - displayName desc
                - extensionAttributes
                - extensionAttributes desc
                - isCompliant
                - isCompliant desc
                - isManaged
                - isManaged desc
                - onPremisesLastSyncDateTime
                - onPremisesLastSyncDateTime desc
                - onPremisesSyncEnabled
                - onPremisesSyncEnabled desc
                - operatingSystem
                - operatingSystem desc
                - operatingSystemVersion
                - operatingSystemVersion desc
                - physicalIds
                - physicalIds desc
                - profileType
                - profileType desc
                - systemLabels
                - systemLabels desc
                - trustType
                - trustType desc
                - Name
                - Name desc
                - Manufacturer
                - Manufacturer desc
                - Model
                - Model desc
                - Kind
                - Kind desc
                - Status
                - Status desc
                - Platform
                - Platform desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - deletedDateTime
                - accountEnabled
                - alternativeSecurityIds
                - approximateLastSignInDateTime
                - complianceExpirationDateTime
                - deviceId
                - deviceMetadata
                - deviceVersion
                - displayName
                - extensionAttributes
                - isCompliant
                - isManaged
                - onPremisesLastSyncDateTime
                - onPremisesSyncEnabled
                - operatingSystem
                - operatingSystemVersion
                - physicalIds
                - profileType
                - systemLabels
                - trustType
                - Name
                - Manufacturer
                - Model
                - Kind
                - Status
                - Platform
                - memberOf
                - registeredOwners
                - registeredUsers
                - transitiveMemberOf
                - extensions
                - commands
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - memberOf
                - registeredOwners
                - registeredUsers
                - transitiveMemberOf
                - extensions
                - commands
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of device
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.device'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - users.device
      summary: Create new navigation property to devices for users
      operationId: users_CreateDevices
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.device'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.device'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/users/{user-id}/devices/{device-id}':
    get:
      tags:
        - users.device
      summary: Get devices from users
      operationId: users_GetDevices
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: device-id
          in: path
          description: 'key: device-id of device'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: device
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - deletedDateTime
                - accountEnabled
                - alternativeSecurityIds
                - approximateLastSignInDateTime
                - complianceExpirationDateTime
                - deviceId
                - deviceMetadata
                - deviceVersion
                - displayName
                - extensionAttributes
                - isCompliant
                - isManaged
                - onPremisesLastSyncDateTime
                - onPremisesSyncEnabled
                - operatingSystem
                - operatingSystemVersion
                - physicalIds
                - profileType
                - systemLabels
                - trustType
                - Name
                - Manufacturer
                - Model
                - Kind
                - Status
                - Platform
                - memberOf
                - registeredOwners
                - registeredUsers
                - transitiveMemberOf
                - extensions
                - commands
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - memberOf
                - registeredOwners
                - registeredUsers
                - transitiveMemberOf
                - extensions
                - commands
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.device'
          links:
            memberOf:
              operationId: user.devices.GetMemberOf
              parameters:
                user-id: $request.path.user-id
                device-id: $request.path.device-id
                directoryObject-id: $response.body#/id
            registeredOwners:
              operationId: user.devices.GetRegisteredOwners
              parameters:
                user-id: $request.path.user-id
                device-id: $request.path.device-id
                directoryObject-id: $response.body#/id
            registeredUsers:
              operationId: user.devices.GetRegisteredUsers
              parameters:
                user-id: $request.path.user-id
                device-id: $request.path.device-id
                directoryObject-id: $response.body#/id
            transitiveMemberOf:
              operationId: user.devices.GetTransitiveMemberOf
              parameters:
                user-id: $request.path.user-id
                device-id: $request.path.device-id
                directoryObject-id: $response.body#/id
            extensions:
              operationId: user.devices.GetExtensions
              parameters:
                user-id: $request.path.user-id
                device-id: $request.path.device-id
                extension-id: $response.body#/id
            commands:
              operationId: user.devices.GetCommands
              parameters:
                user-id: $request.path.user-id
                device-id: $request.path.device-id
                command-id: $response.body#/id
        default:
          $ref: '#/components/responses/error'
    patch:
      tags:
        - users.device
      summary: Update the navigation property devices in users
      operationId: users_UpdateDevices
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: device-id
          in: path
          description: 'key: device-id of device'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: device
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.device'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.device:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.directoryObject'
        - title: device
          type: object
          properties:
            accountEnabled:
              type: boolean
              description: 'true if the account is enabled; otherwise, false. Required.'
              nullable: true
            alternativeSecurityIds:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.alternativeSecurityId'
              description: For internal use only. Not nullable.
            approximateLastSignInDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              description: 'The timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: ''2014-01-01T00:00:00Z''. Read-only.'
              format: date-time
              nullable: true
            complianceExpirationDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              description: 'The timestamp when the device is no longer deemed compliant. The timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: ''2014-01-01T00:00:00Z''. Read-only.'
              format: date-time
              nullable: true
            deviceId:
              type: string
              description: Unique identifier set by Azure Device Registration Service at the time of registration.
              nullable: true
            deviceMetadata:
              type: string
              description: For interal use only. Set to null.
              nullable: true
            deviceVersion:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              description: For interal use only.
              format: int32
              nullable: true
            displayName:
              type: string
              description: The display name for the device. Required.
              nullable: true
            extensionAttributes:
              $ref: '#/components/schemas/microsoft.graph.onPremisesExtensionAttributes'
            isCompliant:
              type: boolean
              description: 'true if the device complies with Mobile Device Management (MDM) policies; otherwise, false. Read-only. This can only be updated by Intune for any device OS type or by an approved MDM app for Windows OS devices.'
              nullable: true
            isManaged:
              type: boolean
              description: 'true if the device is managed by a Mobile Device Management (MDM) app; otherwise, false. This can only be updated by Intune for any device OS type or by an approved MDM app for Windows OS devices.'
              nullable: true
            onPremisesLastSyncDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              description: 'The last time at which the object was synced with the on-premises directory.The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: ''2014-01-01T00:00:00Z'' Read-only.'
              format: date-time
              nullable: true
            onPremisesSyncEnabled:
              type: boolean
              description: true if this object is synced from an on-premises directory; false if this object was originally synced from an on-premises directory but is no longer synced; null if this object has never been synced from an on-premises directory (default). Read-only.
              nullable: true
            operatingSystem:
              type: string
              description: The type of operating system on the device. Required.
              nullable: true
            operatingSystemVersion:
              type: string
              description: The version of the operating system on the device. Required.
              nullable: true
            physicalIds:
              type: array
              items:
                type: string
              description: For interal use only. Not nullable.
            profileType:
              type: string
              description: The profile type of the device. Possible values:RegisteredDevice (default)SecureVMPrinterSharedIoT
              nullable: true
            systemLabels:
              type: array
              items:
                type: string
              description: List of labels applied to the device by the system.
            trustType:
              type: string
              description: 'Type of trust for the joined device. Read-only. Possible values: Workplace - indicates bring your own personal devicesAzureAd - Cloud only joined devicesServerAd - on-premises domain joined devices joined to Azure AD. For more details, see Introduction to device management in Azure Active Directory'
              nullable: true
            Name:
              type: string
              nullable: true
            Manufacturer:
              type: string
              nullable: true
            Model:
              type: string
              nullable: true
            Kind:
              type: string
              nullable: true
            Status:
              type: string
              nullable: true
            Platform:
              type: string
              nullable: true
            memberOf:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.directoryObject'
              description: 'Groups that this group is a member of. HTTP Methods: GET (supported for all groups). Read-only. Nullable.'
            registeredOwners:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.directoryObject'
              description: 'The user that cloud joined the device or registered their personal device. The registered owner is set at the time of registration. Currently, there can be only one owner. Read-only. Nullable.'
            registeredUsers:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.directoryObject'
              description: 'Collection of registered users of the device. For cloud joined devices and registered personal devices, registered users are set to the same value as registered owners at the time of registration. Read-only. Nullable.'
            transitiveMemberOf:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.directoryObject'
            extensions:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.extension'
              description: The collection of open extensions defined for the device. Read-only. Nullable.
            commands:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.command'
          description: Represents an Azure Active Directory object. The directoryObject type is the base type for many other directory entity types.
      example:
        id: string (identifier)
        deletedDateTime: string (timestamp)
        accountEnabled: true
        alternativeSecurityIds:
          - '@odata.type': microsoft.graph.alternativeSecurityId
        approximateLastSignInDateTime: string (timestamp)
        complianceExpirationDateTime: string (timestamp)
        deviceId: string
        deviceMetadata: string
        deviceVersion: integer
        displayName: string
        extensionAttributes:
          '@odata.type': microsoft.graph.onPremisesExtensionAttributes
        isCompliant: true
        isManaged: true
        onPremisesLastSyncDateTime: string (timestamp)
        onPremisesSyncEnabled: true
        operatingSystem: string
        operatingSystemVersion: string
        physicalIds:
          - string
        profileType: string
        systemLabels:
          - string
        trustType: string
        Name: string
        Manufacturer: string
        Model: string
        Kind: string
        Status: string
        Platform: string
        memberOf:
          - '@odata.type': microsoft.graph.directoryObject
        registeredOwners:
          - '@odata.type': microsoft.graph.directoryObject
        registeredUsers:
          - '@odata.type': microsoft.graph.directoryObject
        transitiveMemberOf:
          - '@odata.type': microsoft.graph.directoryObject
        extensions:
          - '@odata.type': microsoft.graph.extension
        commands:
          - '@odata.type': microsoft.graph.command
    microsoft.graph.directoryObject:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: directoryObject
          type: object
          properties:
            deletedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
          description: Represents an Azure Active Directory object. The directoryObject type is the base type for many other directory entity types.
      example:
        id: string (identifier)
        deletedDateTime: string (timestamp)
    microsoft.graph.alternativeSecurityId:
      title: alternativeSecurityId
      type: object
      properties:
        type:
          maximum: 2147483647
          minimum: -2147483648
          type: integer
          description: For internal use only
          format: int32
          nullable: true
        identityProvider:
          type: string
          description: For internal use only
          nullable: true
        key:
          type: string
          description: For internal use only
          format: base64url
          nullable: true
      example:
        type: integer
        identityProvider: string
        key: string
    microsoft.graph.onPremisesExtensionAttributes:
      title: onPremisesExtensionAttributes
      type: object
      properties:
        extensionAttribute1:
          type: string
          description: First customizable extension attribute.
          nullable: true
        extensionAttribute2:
          type: string
          description: Second customizable extension attribute.
          nullable: true
        extensionAttribute3:
          type: string
          description: Third customizable extension attribute.
          nullable: true
        extensionAttribute4:
          type: string
          description: Fourth customizable extension attribute.
          nullable: true
        extensionAttribute5:
          type: string
          description: Fifth customizable extension attribute.
          nullable: true
        extensionAttribute6:
          type: string
          description: Sixth customizable extension attribute.
          nullable: true
        extensionAttribute7:
          type: string
          description: Seventh customizable extension attribute.
          nullable: true
        extensionAttribute8:
          type: string
          description: Eighth customizable extension attribute.
          nullable: true
        extensionAttribute9:
          type: string
          description: Ninth customizable extension attribute.
          nullable: true
        extensionAttribute10:
          type: string
          description: Tenth customizable extension attribute.
          nullable: true
        extensionAttribute11:
          type: string
          description: Eleventh customizable extension attribute.
          nullable: true
        extensionAttribute12:
          type: string
          description: Twelfth customizable extension attribute.
          nullable: true
        extensionAttribute13:
          type: string
          description: Thirteenth customizable extension attribute.
          nullable: true
        extensionAttribute14:
          type: string
          description: Fourteenth customizable extension attribute.
          nullable: true
        extensionAttribute15:
          type: string
          description: Fifteenth customizable extension attribute.
          nullable: true
      example:
        extensionAttribute1: string
        extensionAttribute2: string
        extensionAttribute3: string
        extensionAttribute4: string
        extensionAttribute5: string
        extensionAttribute6: string
        extensionAttribute7: string
        extensionAttribute8: string
        extensionAttribute9: string
        extensionAttribute10: string
        extensionAttribute11: string
        extensionAttribute12: string
        extensionAttribute13: string
        extensionAttribute14: string
        extensionAttribute15: string
    microsoft.graph.extension:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: extension
          type: object
      example:
        id: string (identifier)
    microsoft.graph.command:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: command
          type: object
          properties:
            Status:
              type: string
              nullable: true
            Type:
              type: string
              nullable: true
            AppServiceName:
              type: string
              nullable: true
            PackageFamilyName:
              type: string
              nullable: true
            Error:
              type: string
              nullable: true
            Payload:
              $ref: '#/components/schemas/microsoft.graph.PayloadRequest'
            PermissionTicket:
              type: string
              nullable: true
            PostBackUri:
              type: string
              nullable: true
            responsepayload:
              $ref: '#/components/schemas/microsoft.graph.payloadResponse'
      example:
        id: string (identifier)
        Status: string
        Type: string
        AppServiceName: string
        PackageFamilyName: string
        Error: string
        Payload:
          '@odata.type': microsoft.graph.PayloadRequest
        PermissionTicket: string
        PostBackUri: string
        responsepayload:
          '@odata.type': microsoft.graph.payloadResponse
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
          description: Read-only.
      example:
        id: string (identifier)
    microsoft.graph.PayloadRequest:
      title: PayloadRequest
      type: object
    microsoft.graph.payloadResponse:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: payloadResponse
          type: object
      example:
        id: string (identifier)
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]