openapi: 3.0.1
info:
  title: Identity.Domains
  version: v1.0
servers:
  - url: https://graph.microsoft.com/v1.0/
    description: Core
paths:
  /domains:
    get:
      tags:
        - domains.domain
      summary: Get entities from domains
      operationId: domains.domain_ListDomain
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - authenticationType
                - authenticationType desc
                - availabilityStatus
                - availabilityStatus desc
                - isAdminManaged
                - isAdminManaged desc
                - isDefault
                - isDefault desc
                - isInitial
                - isInitial desc
                - isRoot
                - isRoot desc
                - isVerified
                - isVerified desc
                - manufacturer
                - manufacturer desc
                - model
                - model desc
                - passwordNotificationWindowInDays
                - passwordNotificationWindowInDays desc
                - passwordValidityPeriodInDays
                - passwordValidityPeriodInDays desc
                - supportedServices
                - supportedServices desc
                - state
                - state desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - authenticationType
                - availabilityStatus
                - isAdminManaged
                - isDefault
                - isInitial
                - isRoot
                - isVerified
                - manufacturer
                - model
                - passwordNotificationWindowInDays
                - passwordValidityPeriodInDays
                - supportedServices
                - state
                - serviceConfigurationRecords
                - verificationDnsRecords
                - domainNameReferences
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - serviceConfigurationRecords
                - verificationDnsRecords
                - domainNameReferences
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of domain
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.domain'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - domains.domain
      summary: Add new entity to domains
      operationId: domains.domain_CreateDomain
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.domain'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.domain'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/domains/{domain-id}':
    get:
      tags:
        - domains.domain
      summary: Get entity from domains by key
      operationId: domains.domain_GetDomain
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - authenticationType
                - availabilityStatus
                - isAdminManaged
                - isDefault
                - isInitial
                - isRoot
                - isVerified
                - manufacturer
                - model
                - passwordNotificationWindowInDays
                - passwordValidityPeriodInDays
                - supportedServices
                - state
                - serviceConfigurationRecords
                - verificationDnsRecords
                - domainNameReferences
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
                - serviceConfigurationRecords
                - verificationDnsRecords
                - domainNameReferences
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.domain'
          links:
            serviceConfigurationRecords:
              operationId: domains.GetServiceConfigurationRecords
              parameters:
                domain-id: $request.path.domain-id
                domainDnsRecord-id: $response.body#/id
            verificationDnsRecords:
              operationId: domains.GetVerificationDnsRecords
              parameters:
                domain-id: $request.path.domain-id
                domainDnsRecord-id: $response.body#/id
            domainNameReferences:
              operationId: domains.GetDomainNameReferences
              parameters:
                domain-id: $request.path.domain-id
                directoryObject-id: $response.body#/id
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - domains.domain
      summary: Update entity in domains
      operationId: domains.domain_UpdateDomain
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.domain'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - domains.domain
      summary: Delete entity from domains
      operationId: domains.domain_DeleteDomain
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/domains/{domain-id}/domainNameReferences':
    get:
      tags:
        - domains.directoryObject
      summary: Get domainNameReferences from domains
      operationId: domains_ListDomainNameReferences
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - deletedDateTime
                - deletedDateTime desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - deletedDateTime
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of directoryObject
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.directoryObject'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
  '/domains/{domain-id}/domainNameReferences/{directoryObject-id}':
    get:
      tags:
        - domains.directoryObject
      summary: Get domainNameReferences from domains
      operationId: domains_GetDomainNameReferences
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - name: directoryObject-id
          in: path
          description: 'key: directoryObject-id of directoryObject'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: directoryObject
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - deletedDateTime
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.directoryObject'
        default:
          $ref: '#/components/responses/error'
  '/domains/{domain-id}/microsoft.graph.forceDelete':
    post:
      tags:
        - domains.Actions
      summary: Invoke action forceDelete
      operationId: domains_forceDelete
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
      requestBody:
        description: Action parameters
        content:
          application/json:
            schema:
              type: object
              properties:
                disableUserAccounts:
                  type: boolean
                  default: false
                  nullable: true
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: action
  '/domains/{domain-id}/microsoft.graph.verify':
    post:
      tags:
        - domains.Actions
      summary: Invoke action verify
      operationId: domains_verify
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.domain'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: action
  '/domains/{domain-id}/serviceConfigurationRecords':
    get:
      tags:
        - domains.domainDnsRecord
      summary: Get serviceConfigurationRecords from domains
      operationId: domains_ListServiceConfigurationRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - isOptional
                - isOptional desc
                - label
                - label desc
                - recordType
                - recordType desc
                - supportedService
                - supportedService desc
                - ttl
                - ttl desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isOptional
                - label
                - recordType
                - supportedService
                - ttl
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of domainDnsRecord
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - domains.domainDnsRecord
      summary: Create new navigation property to serviceConfigurationRecords for domains
      operationId: domains_CreateServiceConfigurationRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/domains/{domain-id}/serviceConfigurationRecords/{domainDnsRecord-id}':
    get:
      tags:
        - domains.domainDnsRecord
      summary: Get serviceConfigurationRecords from domains
      operationId: domains_GetServiceConfigurationRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - name: domainDnsRecord-id
          in: path
          description: 'key: domainDnsRecord-id of domainDnsRecord'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domainDnsRecord
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isOptional
                - label
                - recordType
                - supportedService
                - ttl
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        default:
          $ref: '#/components/responses/error'
    patch:
      tags:
        - domains.domainDnsRecord
      summary: Update the navigation property serviceConfigurationRecords in domains
      operationId: domains_UpdateServiceConfigurationRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - name: domainDnsRecord-id
          in: path
          description: 'key: domainDnsRecord-id of domainDnsRecord'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domainDnsRecord
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/domains/{domain-id}/verificationDnsRecords':
    get:
      tags:
        - domains.domainDnsRecord
      summary: Get verificationDnsRecords from domains
      operationId: domains_ListVerificationDnsRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - isOptional
                - isOptional desc
                - label
                - label desc
                - recordType
                - recordType desc
                - supportedService
                - supportedService desc
                - ttl
                - ttl desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isOptional
                - label
                - recordType
                - supportedService
                - ttl
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of domainDnsRecord
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - domains.domainDnsRecord
      summary: Create new navigation property to verificationDnsRecords for domains
      operationId: domains_CreateVerificationDnsRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/domains/{domain-id}/verificationDnsRecords/{domainDnsRecord-id}':
    get:
      tags:
        - domains.domainDnsRecord
      summary: Get verificationDnsRecords from domains
      operationId: domains_GetVerificationDnsRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - name: domainDnsRecord-id
          in: path
          description: 'key: domainDnsRecord-id of domainDnsRecord'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domainDnsRecord
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - isOptional
                - label
                - recordType
                - supportedService
                - ttl
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        default:
          $ref: '#/components/responses/error'
    patch:
      tags:
        - domains.domainDnsRecord
      summary: Update the navigation property verificationDnsRecords in domains
      operationId: domains_UpdateVerificationDnsRecords
      parameters:
        - name: domain-id
          in: path
          description: 'key: domain-id of domain'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domain
        - name: domainDnsRecord-id
          in: path
          description: 'key: domainDnsRecord-id of domainDnsRecord'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: domainDnsRecord
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.domain:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: domain
          type: object
          properties:
            authenticationType:
              type: string
              description: Indicates the configured authentication type for the domain. The value is either Managed or Federated. Managed indicates a cloud managed domain where Azure AD performs user authentication.Federated indicates authentication is federated with an identity provider such as the tenant's on-premises Active Directory via Active Directory Federation Services. This property is read-only and is not nullable.
            availabilityStatus:
              type: string
              description: 'This property is always null except when the verify action is used. When the verify action is used, a domain entity is returned in the response. The availabilityStatus property of the domain entity in the response is either AvailableImmediately or EmailVerifiedDomainTakeoverScheduled.'
              nullable: true
            isAdminManaged:
              type: boolean
              description: 'The value of the property is false if the DNS record management of the domain has been delegated to Office 365. Otherwise, the value is true. Not nullable'
            isDefault:
              type: boolean
              description: True if this is the default domain that is used for user creation. There is only one default domain per company. Not nullable
            isInitial:
              type: boolean
              description: True if this is the initial domain created by Microsoft Online Services (companyname.onmicrosoft.com). There is only one initial domain per company. Not nullable
            isRoot:
              type: boolean
              description: 'True if the domain is a verified root domain. Otherwise, false if the domain is a subdomain or unverified. Not nullable'
            isVerified:
              type: boolean
              description: True if the domain has completed domain ownership verification. Not nullable
            manufacturer:
              type: string
              nullable: true
            model:
              type: string
              nullable: true
            passwordNotificationWindowInDays:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              description: 'Specifies the number of days before a user receives notification that their password will expire. If the property is not set, a default value of 14 days will be used.'
              format: int32
              nullable: true
            passwordValidityPeriodInDays:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              description: 'Specifies the length of time that a password is valid before it must be changed. If the property is not set, a default value of 90 days will be used.'
              format: int32
              nullable: true
            supportedServices:
              type: array
              items:
                type: string
              description: 'The capabilities assigned to the domain.Can include 0, 1 or more of following values: Email, Sharepoint, EmailInternalRelayOnly, OfficeCommunicationsOnline, SharePointDefaultDomain, FullRedelegation, SharePointPublic, OrgIdAuthentication, Yammer, Intune The values which you can add/remove using Graph API include: Email, OfficeCommunicationsOnline, YammerNot nullable'
            state:
              $ref: '#/components/schemas/microsoft.graph.domainState'
            serviceConfigurationRecords:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
              description: 'DNS records the customer adds to the DNS zone file of the domain before the domain can be used by Microsoft Online services.Read-only, Nullable'
            verificationDnsRecords:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.domainDnsRecord'
              description: 'DNS records that the customer adds to the DNS zone file of the domain before the customer can complete domain ownership verification with Azure AD.Read-only, Nullable'
            domainNameReferences:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.directoryObject'
              description: 'Read-only, Nullable'
      example:
        id: string (identifier)
        authenticationType: string
        availabilityStatus: string
        isAdminManaged: true
        isDefault: true
        isInitial: true
        isRoot: true
        isVerified: true
        manufacturer: string
        model: string
        passwordNotificationWindowInDays: integer
        passwordValidityPeriodInDays: integer
        supportedServices:
          - string
        state:
          '@odata.type': microsoft.graph.domainState
        serviceConfigurationRecords:
          - '@odata.type': microsoft.graph.domainDnsRecord
        verificationDnsRecords:
          - '@odata.type': microsoft.graph.domainDnsRecord
        domainNameReferences:
          - '@odata.type': microsoft.graph.directoryObject
    microsoft.graph.directoryObject:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: directoryObject
          type: object
          properties:
            deletedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
          description: Represents an Azure Active Directory object. The directoryObject type is the base type for many other directory entity types.
      example:
        id: string (identifier)
        deletedDateTime: string (timestamp)
    microsoft.graph.domainDnsRecord:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: domainDnsRecord
          type: object
          properties:
            isOptional:
              type: boolean
              description: 'If false, this record must be configured by the customer at the DNS host for Microsoft Online Services to operate correctly with the domain.'
            label:
              type: string
              description: Value used when configuring the name of the DNS record at the DNS host.
            recordType:
              type: string
              description: 'Indicates what type of DNS record this entity represents.The value can be one of the following: CName, Mx, Srv, TxtKey'
              nullable: true
            supportedService:
              type: string
              description: 'Microsoft Online Service or feature that has a dependency on this DNS record.Can be one of the following values: null, Email, Sharepoint, EmailInternalRelayOnly, OfficeCommunicationsOnline, SharePointDefaultDomain, FullRedelegation, SharePointPublic, OrgIdAuthentication, Yammer, Intune'
            ttl:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              description: Value to use when configuring the time-to-live (ttl) property of the DNS record at the DNS host. Not nullable
              format: int32
      example:
        id: string (identifier)
        isOptional: true
        label: string
        recordType: string
        supportedService: string
        ttl: integer
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
          description: Read-only.
      example:
        id: string (identifier)
    microsoft.graph.domainState:
      title: domainState
      type: object
      properties:
        status:
          type: string
          description: Current status of the operation.  Scheduled - Operation has been scheduled but has not started.  InProgress - Task has started and is in progress.  Failed - Operation has failed.
          nullable: true
        operation:
          type: string
          description: Type of asynchronous operation. The values can be ForceDelete or Verification
          nullable: true
        lastActionDateTime:
          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
          type: string
          description: 'Timestamp for when the last activity occurred. The value is updated when an operation is scheduled, the asynchronous task starts, and when the operation completes.'
          format: date-time
          nullable: true
      example:
        status: string
        operation: string
        lastActionDateTime: string (timestamp)
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]