openapi: 3.0.1
info:
  title: OnlineMeetings
  version: v1.0
servers:
  - url: https://graph.microsoft.com/v1.0/
    description: Core
paths:
  '/users/{user-id}/onlineMeetings':
    get:
      tags:
        - users.onlineMeeting
      summary: Get onlineMeetings from users
      operationId: users_ListOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - creationDateTime
                - creationDateTime desc
                - startDateTime
                - startDateTime desc
                - endDateTime
                - endDateTime desc
                - joinWebUrl
                - joinWebUrl desc
                - subject
                - subject desc
                - participants
                - participants desc
                - audioConferencing
                - audioConferencing desc
                - chatInfo
                - chatInfo desc
                - videoTeleconferenceId
                - videoTeleconferenceId desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - creationDateTime
                - startDateTime
                - endDateTime
                - joinWebUrl
                - subject
                - participants
                - audioConferencing
                - chatInfo
                - videoTeleconferenceId
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of onlineMeeting
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - users.onlineMeeting
      summary: Create new navigation property to onlineMeetings for users
      operationId: users_CreateOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/users/{user-id}/onlineMeetings/{onlineMeeting-id}':
    get:
      tags:
        - users.onlineMeeting
      summary: Get onlineMeetings from users
      operationId: users_GetOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: onlineMeeting-id
          in: path
          description: 'key: onlineMeeting-id of onlineMeeting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: onlineMeeting
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - creationDateTime
                - startDateTime
                - endDateTime
                - joinWebUrl
                - subject
                - participants
                - audioConferencing
                - chatInfo
                - videoTeleconferenceId
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        default:
          $ref: '#/components/responses/error'
    patch:
      tags:
        - users.onlineMeeting
      summary: Update the navigation property onlineMeetings in users
      operationId: users_UpdateOnlineMeetings
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: onlineMeeting-id
          in: path
          description: 'key: onlineMeeting-id of onlineMeeting'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: onlineMeeting
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.onlineMeeting'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.onlineMeeting:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: onlineMeeting
          type: object
          properties:
            creationDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              description: The meeting creation time in UTC. Read-only.
              format: date-time
              nullable: true
            startDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              description: The meeting start time in UTC.
              format: date-time
              nullable: true
            endDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              description: The meeting end time in UTC.
              format: date-time
              nullable: true
            joinWebUrl:
              type: string
              description: The join URL of the online meeting. Read-only.
              nullable: true
            subject:
              type: string
              description: The subject of the online meeting.
              nullable: true
            participants:
              $ref: '#/components/schemas/microsoft.graph.meetingParticipants'
            audioConferencing:
              $ref: '#/components/schemas/microsoft.graph.audioConferencing'
            chatInfo:
              $ref: '#/components/schemas/microsoft.graph.chatInfo'
            videoTeleconferenceId:
              type: string
              description: The video teleconferencing ID. Read-only.
              nullable: true
      example:
        id: string (identifier)
        creationDateTime: string (timestamp)
        startDateTime: string (timestamp)
        endDateTime: string (timestamp)
        joinWebUrl: string
        subject: string
        participants:
          '@odata.type': microsoft.graph.meetingParticipants
        audioConferencing:
          '@odata.type': microsoft.graph.audioConferencing
        chatInfo:
          '@odata.type': microsoft.graph.chatInfo
        videoTeleconferenceId: string
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
          description: Read-only.
      example:
        id: string (identifier)
    microsoft.graph.meetingParticipants:
      title: meetingParticipants
      type: object
      properties:
        organizer:
          $ref: '#/components/schemas/microsoft.graph.meetingParticipantInfo'
        attendees:
          type: array
          items:
            $ref: '#/components/schemas/microsoft.graph.meetingParticipantInfo'
      example:
        organizer:
          '@odata.type': microsoft.graph.meetingParticipantInfo
        attendees:
          - '@odata.type': microsoft.graph.meetingParticipantInfo
    microsoft.graph.audioConferencing:
      title: audioConferencing
      type: object
      properties:
        conferenceId:
          type: string
          nullable: true
        tollNumber:
          type: string
          description: The toll number that connects to the Audio Conference Provider.
          nullable: true
        tollFreeNumber:
          type: string
          description: The toll-free number that connects to the Audio Conference Provider.
          nullable: true
        dialinUrl:
          type: string
          description: A URL to the externally-accessible web page that contains dial-in information.
          nullable: true
      example:
        conferenceId: string
        tollNumber: string
        tollFreeNumber: string
        dialinUrl: string
    microsoft.graph.chatInfo:
      title: chatInfo
      type: object
      properties:
        threadId:
          type: string
          description: The unique identifier for a thread in Microsoft Teams.
          nullable: true
        messageId:
          type: string
          description: The unique identifier of a message in a Microsoft Teams channel.
          nullable: true
        replyChainMessageId:
          type: string
          description: The ID of the reply message.
          nullable: true
      example:
        threadId: string
        messageId: string
        replyChainMessageId: string
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    microsoft.graph.meetingParticipantInfo:
      title: meetingParticipantInfo
      type: object
      properties:
        identity:
          $ref: '#/components/schemas/microsoft.graph.identitySet'
        upn:
          type: string
          description: User principal name of the participant.
          nullable: true
      example:
        identity:
          '@odata.type': microsoft.graph.identitySet
        upn: string
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    microsoft.graph.identitySet:
      title: identitySet
      type: object
      properties:
        application:
          $ref: '#/components/schemas/microsoft.graph.identity'
        device:
          $ref: '#/components/schemas/microsoft.graph.identity'
        user:
          $ref: '#/components/schemas/microsoft.graph.identity'
      example:
        application:
          '@odata.type': microsoft.graph.identity
        device:
          '@odata.type': microsoft.graph.identity
        user:
          '@odata.type': microsoft.graph.identity
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
    microsoft.graph.identity:
      title: identity
      type: object
      properties:
        displayName:
          type: string
          description: 'The identity''s display name. Note that this may not always be available or up to date. For example, if a user changes their display name, the API may show the new value in a future response, but the items associated with the user won''t show up as having changed when using delta.'
          nullable: true
        id:
          type: string
          description: Unique identifier for the identity.
          nullable: true
      example:
        displayName: string
        id: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]