openapi: 3.0.1
info:
  title: Users.People
  version: v1.0
servers:
  - url: https://graph.microsoft.com/v1.0/
    description: Core
paths:
  '/users/{user-id}/people':
    get:
      tags:
        - users.person
      summary: Get people from users
      operationId: users_ListPeople
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - displayName
                - displayName desc
                - givenName
                - givenName desc
                - surname
                - surname desc
                - birthday
                - birthday desc
                - personNotes
                - personNotes desc
                - isFavorite
                - isFavorite desc
                - scoredEmailAddresses
                - scoredEmailAddresses desc
                - phones
                - phones desc
                - postalAddresses
                - postalAddresses desc
                - websites
                - websites desc
                - jobTitle
                - jobTitle desc
                - companyName
                - companyName desc
                - yomiCompany
                - yomiCompany desc
                - department
                - department desc
                - officeLocation
                - officeLocation desc
                - profession
                - profession desc
                - personType
                - personType desc
                - userPrincipalName
                - userPrincipalName desc
                - imAddress
                - imAddress desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - givenName
                - surname
                - birthday
                - personNotes
                - isFavorite
                - scoredEmailAddresses
                - phones
                - postalAddresses
                - websites
                - jobTitle
                - companyName
                - yomiCompany
                - department
                - officeLocation
                - profession
                - personType
                - userPrincipalName
                - imAddress
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of person
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.person'
                  '@odata.nextLink':
                    type: string
        default:
          $ref: '#/components/responses/error'
      x-ms-pageable:
        nextLinkName: '@odata.nextLink'
        operationName: listMore
      x-ms-docs-operation-type: operation
    post:
      tags:
        - users.person
      summary: Create new navigation property to people for users
      operationId: users_CreatePeople
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.person'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.person'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/users/{user-id}/people/{person-id}':
    get:
      tags:
        - users.person
      summary: Get people from users
      operationId: users_GetPeople
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: person-id
          in: path
          description: 'key: person-id of person'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: person
        - name: $select
          in: query
          description: Select properties to be returned
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - displayName
                - givenName
                - surname
                - birthday
                - personNotes
                - isFavorite
                - scoredEmailAddresses
                - phones
                - postalAddresses
                - websites
                - jobTitle
                - companyName
                - yomiCompany
                - department
                - officeLocation
                - profession
                - personType
                - userPrincipalName
                - imAddress
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: form
          explode: false
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.person'
        default:
          $ref: '#/components/responses/error'
    patch:
      tags:
        - users.person
      summary: Update the navigation property people in users
      operationId: users_UpdatePeople
      parameters:
        - name: user-id
          in: path
          description: 'key: user-id of user'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: user
        - name: person-id
          in: path
          description: 'key: person-id of person'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: person
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.person'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.person:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: person
          type: object
          properties:
            displayName:
              type: string
              description: The person's display name.
              nullable: true
            givenName:
              type: string
              description: The person's given name.
              nullable: true
            surname:
              type: string
              description: The person's surname.
              nullable: true
            birthday:
              type: string
              description: The person's birthday.
              nullable: true
            personNotes:
              type: string
              description: Free-form notes that the user has taken about this person.
              nullable: true
            isFavorite:
              type: boolean
              description: true if the user has flagged this person as a favorite.
              nullable: true
            scoredEmailAddresses:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.scoredEmailAddress'
              description: The person's email addresses.
            phones:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.phone'
              description: The person's phone numbers.
            postalAddresses:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.location'
              description: The person's addresses.
            websites:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.website'
              description: The person's websites.
            jobTitle:
              type: string
              description: The person's job title.
              nullable: true
            companyName:
              type: string
              description: The name of the person's company.
              nullable: true
            yomiCompany:
              type: string
              description: The phonetic Japanese name of the person's company.
              nullable: true
            department:
              type: string
              description: The person's department.
              nullable: true
            officeLocation:
              type: string
              description: The location of the person's office.
              nullable: true
            profession:
              type: string
              description: The person's profession.
              nullable: true
            personType:
              $ref: '#/components/schemas/microsoft.graph.personType'
            userPrincipalName:
              type: string
              description: 'The user principal name (UPN) of the person. The UPN is an Internet-style login name for the person based on the Internet standard RFC 822. By convention, this should map to the person''s email name. The general format is alias@domain.'
              nullable: true
            imAddress:
              type: string
              description: The instant message voice over IP (VOIP) session initiation protocol (SIP) address for the user. Read-only.
              nullable: true
      example:
        id: string (identifier)
        displayName: string
        givenName: string
        surname: string
        birthday: string
        personNotes: string
        isFavorite: true
        scoredEmailAddresses:
          - '@odata.type': microsoft.graph.scoredEmailAddress
        phones:
          - '@odata.type': microsoft.graph.phone
        postalAddresses:
          - '@odata.type': microsoft.graph.location
        websites:
          - '@odata.type': microsoft.graph.website
        jobTitle: string
        companyName: string
        yomiCompany: string
        department: string
        officeLocation: string
        profession: string
        personType:
          '@odata.type': microsoft.graph.personType
        userPrincipalName: string
        imAddress: string
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
          description: Read-only.
      example:
        id: string (identifier)
    microsoft.graph.scoredEmailAddress:
      title: scoredEmailAddress
      type: object
      properties:
        address:
          type: string
          description: The email address.
          nullable: true
        relevanceScore:
          type: number
          description: 'The relevance score of the email address. A relevance score is used as a sort key, in relation to the other returned results. A higher relevance score value corresponds to a more relevant result. Relevance is determined by the user’s communication and collaboration patterns and business relationships.'
          format: double
          nullable: true
        selectionLikelihood:
          $ref: '#/components/schemas/microsoft.graph.selectionLikelihoodInfo'
        itemId:
          type: string
          nullable: true
      example:
        address: string
        relevanceScore: double
        selectionLikelihood:
          '@odata.type': microsoft.graph.selectionLikelihoodInfo
        itemId: string
    microsoft.graph.phone:
      title: phone
      type: object
      properties:
        type:
          $ref: '#/components/schemas/microsoft.graph.phoneType'
        number:
          type: string
          description: The phone number.
          nullable: true
        region:
          type: string
          nullable: true
        language:
          type: string
          nullable: true
      example:
        type:
          '@odata.type': microsoft.graph.phoneType
        number: string
        region: string
        language: string
    microsoft.graph.location:
      title: location
      type: object
      properties:
        displayName:
          type: string
          description: The name associated with the location.
          nullable: true
        locationEmailAddress:
          type: string
          description: Optional email address of the location.
          nullable: true
        address:
          $ref: '#/components/schemas/microsoft.graph.physicalAddress'
        locationUri:
          type: string
          description: Optional URI representing the location.
          nullable: true
        coordinates:
          $ref: '#/components/schemas/microsoft.graph.outlookGeoCoordinates'
        locationType:
          $ref: '#/components/schemas/microsoft.graph.locationType'
        uniqueId:
          type: string
          description: For internal use only.
          nullable: true
        uniqueIdType:
          $ref: '#/components/schemas/microsoft.graph.locationUniqueIdType'
      example:
        displayName: string
        locationEmailAddress: string
        address:
          '@odata.type': microsoft.graph.physicalAddress
        locationUri: string
        coordinates:
          '@odata.type': microsoft.graph.outlookGeoCoordinates
        locationType:
          '@odata.type': microsoft.graph.locationType
        uniqueId: string
        uniqueIdType:
          '@odata.type': microsoft.graph.locationUniqueIdType
    microsoft.graph.website:
      title: website
      type: object
      properties:
        type:
          $ref: '#/components/schemas/microsoft.graph.websiteType'
        address:
          type: string
          description: The URL of the website.
          nullable: true
        displayName:
          type: string
          description: The display name of the web site.
          nullable: true
      example:
        type:
          '@odata.type': microsoft.graph.websiteType
        address: string
        displayName: string
    microsoft.graph.personType:
      title: personType
      type: object
      properties:
        class:
          type: string
          description: 'The type of data source, such as Person.'
          nullable: true
        subclass:
          type: string
          description: 'The secondary type of data source, such as OrganizationUser.'
          nullable: true
      example:
        class: string
        subclass: string
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    microsoft.graph.selectionLikelihoodInfo:
      title: selectionLikelihoodInfo
      enum:
        - notSpecified
        - high
      type: string
    microsoft.graph.phoneType:
      title: phoneType
      enum:
        - home
        - business
        - mobile
        - other
        - assistant
        - homeFax
        - businessFax
        - otherFax
        - pager
        - radio
      type: string
    microsoft.graph.physicalAddress:
      title: physicalAddress
      type: object
      properties:
        street:
          type: string
          description: The street.
          nullable: true
        city:
          type: string
          description: The city.
          nullable: true
        state:
          type: string
          description: The state.
          nullable: true
        countryOrRegion:
          type: string
          description: 'The country or region. It''s a free-format string value, for example, ''United States''.'
          nullable: true
        postalCode:
          type: string
          description: The postal code.
          nullable: true
      example:
        street: string
        city: string
        state: string
        countryOrRegion: string
        postalCode: string
    microsoft.graph.outlookGeoCoordinates:
      title: outlookGeoCoordinates
      type: object
      properties:
        latitude:
          type: number
          description: The latitude of the location.
          format: double
          nullable: true
        longitude:
          type: number
          description: The longitude of the location.
          format: double
          nullable: true
        accuracy:
          type: number
          description: 'The accuracy of the latitude and longitude. As an example, the accuracy can be measured in meters, such as the latitude and longitude are accurate to within 50 meters.'
          format: double
          nullable: true
        altitude:
          type: number
          description: The altitude of the location.
          format: double
          nullable: true
        altitudeAccuracy:
          type: number
          description: The accuracy of the altitude.
          format: double
          nullable: true
      example:
        latitude: double
        longitude: double
        accuracy: double
        altitude: double
        altitudeAccuracy: double
    microsoft.graph.locationType:
      title: locationType
      enum:
        - default
        - conferenceRoom
        - homeAddress
        - businessAddress
        - geoCoordinates
        - streetAddress
        - hotel
        - restaurant
        - localBusiness
        - postalAddress
      type: string
    microsoft.graph.locationUniqueIdType:
      title: locationUniqueIdType
      enum:
        - unknown
        - locationStore
        - directory
        - private
        - bing
      type: string
    microsoft.graph.websiteType:
      title: websiteType
      enum:
        - other
        - home
        - work
        - blog
        - profile
      type: string
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]